### ISSUE TITLE
IBM JRE fails to install with admin buildpack

### ISSUE THREAD

**Issue by davidcurrie** [cloudfoundry/ibm-websphere-liberty-buildpack#246] opened 2015-09-22 14:50 UTC
Commit 915400c613308995e147627e5053eb5edf9a792b modifed the IBM JRE processing as a result of a fix that went in to the installer which meant that it would honor the provided install location rather than unpacking in to the current directory. This meant that .bin file didn't need to be copied out of the read-only admin_cache before use and the results didn't need to be copied in to the correct location. Unfortunately the fix appears to have stopped creating the response.properties file in the temporary directory and instead uses the directory containing the .bin. This works in the online case but not for an admin buildpack.

E, [2015-09-22T08:04:42.479925 #47] ERROR -- /var/vcap/data/dea_next/admin_buildpacks/5400c51d-3576-452f-a147-c55c53709820_b3b5d542c29f67f48a43192cf73b39c277a3ff4e/lib/liberty_buildpack/buildpack.rb:50:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<Errno::EROFS: Read-only file system - /var/vcap/data/dea_next/admin_buildpacks/5400c51d-3576-452f-a147-c55c53709820_b3b5d542c29f67f48a43192cf73b39c277a3ff4e/admin_cache/response.properties>
Read-only file system - /var/vcap/data/dea_next/admin_buildpacks/5400c51d-3576-452f-a147-c55c53709820_b3b5d542c29f67f48a43192cf73b39c277a3ff4e/admin_cache/response.properties
         Expanding JRE to .java ... Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed

**Comment by jgawor** [comment] 2015-09-22 20:11
This should be fixed by #247.

**Comment by jgawor** [comment] 2015-09-23 17:54
Looks like the problem is still there. After the previous fix, now it fails when doing chmod() operation.

**Comment by jgawor** [comment] 2015-09-28 14:09
Finally resolved by #249.

**Closed by jgawor** 2015-09-28 14:09 UTC
Labels: bug
